<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Aigamo.MatchGenerator" Version="0.0.0-preview026" />
		<PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
		<PackageVersion Include="System.Text.Json" Version="8.0.5" />
		<PackageVersion Include="coverlet.collector" Version="6.0.4" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageVersion Include="xunit" Version="2.9.3" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>
</Project>
